PREFIX dbpediaO: <http://dbpedia.org/ontology/>

select distinct ?Entity ?descricao where {
    ?Entity a dbo:Disease.
	?Entity dbo:abstract ?descricao.
	FILTER (lang(?descricao) = 'pt')
    FILTER (?descricao like '%{name}%')
} LIMIT 100