PREFIX dbpediaO: <http://dbpedia.org/ontology/>

select distinct ?Entity

?name
?descricao
?Imagem
CONCAT('http://apps.who.int/classifications/icd10/browse/2010/en#/', ?linkicd10) as ?linkicd10

where {
    ?Entity a dbo:Disease.
    ?Entity dbo:abstract ?descricao.
    ?Entity rdfs:label ?name.
    OPTIONAL { ?Entity dbo:icd10 ?linkicd10 }
    OPTIONAL { ?Entity dbo:thumbnail ?Imagem }
	FILTER (lang(?name) = '{lang}')
	FILTER (lang(?descricao) = '{lang}')
    FILTER (?Entity like '{uri}')
}
LIMIT 100