PREFIX dbpediaO: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?Entity ?Nome  where {
    ?Entity a dbo:Disease.
	?Entity rdfs:label ?Nome.
	?Entity dbo:abstract ?Descricao.
	FILTER (lang(?Nome) = 'pt')
	FILTER (lang(?Descricao) = 'pt')
    FILTER (lcase(?Descricao) like lcase('%{name}%'))
} LIMIT 100